"""Integration tests: verify that CPL generated by graph-to-cpl compiles
through Contract.from_source() and produces the correct runtime graph.

These tests replicate the graph structures from the JS unit tests,
feed the expected CPL output through the Complier parser, and assert
the resulting compiled workflow has the right nodes, edges, and structure.
"""

from __future__ import annotations

import pytest

from complier import Contract


# ── Helpers ──

def get_workflow(cpl: str, name: str):
    """Compile CPL and return the named CompiledWorkflow."""
    contract = Contract.from_source(cpl)
    assert name in contract.workflows, f"Workflow '{name}' not found in {list(contract.workflows.keys())}"
    return contract.workflows[name]


def walk_linear(workflow, start_id: str | None = None) -> list:
    """Walk from start through next_ids collecting nodes (linear path only)."""
    nodes = workflow.nodes
    current = start_id or workflow.start_node_id
    result = []
    visited = set()
    while current and current not in visited:
        visited.add(current)
        node = nodes[current]
        result.append(node)
        nexts = node.next_ids
        current = nexts[0] if len(nexts) == 1 else None
    return result


def find_nodes_by_type(workflow, type_name: str) -> list:
    """Find all nodes of a given type in the workflow."""
    return [n for n in workflow.nodes.values() if type(n).__name__ == type_name]


# ── Single tool ──

class TestSingleTool:
    def test_compiles(self):
        cpl = 'workflow "single"\n    | fetch_data\n'
        wf = get_workflow(cpl, "single")
        tools = find_nodes_by_type(wf, "ToolNode")
        assert len(tools) == 1
        assert tools[0].tool_name == "fetch_data"

    def test_unnamed_tool(self):
        cpl = 'workflow "unnamed"\n    | unnamed_tool\n'
        wf = get_workflow(cpl, "unnamed")
        tools = find_nodes_by_type(wf, "ToolNode")
        assert len(tools) == 1
        assert tools[0].tool_name == "unnamed_tool"


# ── Linear sequence ──

class TestLinearSequence:
    def test_three_steps_order(self):
        cpl = (
            'workflow "linear"\n'
            "    | step_a\n"
            "    | step_b\n"
            "    | step_c\n"
        )
        wf = get_workflow(cpl, "linear")
        tools = find_nodes_by_type(wf, "ToolNode")
        assert len(tools) == 3
        names = [t.tool_name for t in tools]
        assert "step_a" in names
        assert "step_b" in names
        assert "step_c" in names

        # Verify ordering by walking the graph
        path = walk_linear(wf)
        tool_names = [n.tool_name for n in path if type(n).__name__ == "ToolNode"]
        assert tool_names == ["step_a", "step_b", "step_c"]

    def test_ten_steps(self):
        steps = "\n".join(f"    | tool_{i}" for i in range(10))
        cpl = f'workflow "long"\n{steps}\n'
        wf = get_workflow(cpl, "long")
        tools = find_nodes_by_type(wf, "ToolNode")
        assert len(tools) == 10


# ── Branch ──

class TestBranch:
    def test_two_when_arms(self):
        cpl = (
            'workflow "branching"\n'
            "    | @branch\n"
            '        -when "is_premium"\n'
            "            | premium_flow\n"
            '        -when "is_trial"\n'
            "            | trial_flow\n"
        )
        wf = get_workflow(cpl, "branching")
        branches = find_nodes_by_type(wf, "BranchNode")
        assert len(branches) == 1
        branch = branches[0]
        assert "is_premium" in branch.arms
        assert "is_trial" in branch.arms
        # When no explicit -else, else_node_id points to the BranchBackNode
        # (the compiler always sets it as the implicit fallthrough)

        # Verify arm targets are ToolNodes with correct names
        premium_node = wf.nodes[branch.arms["is_premium"]]
        assert type(premium_node).__name__ == "ToolNode"
        assert premium_node.tool_name == "premium_flow"

        trial_node = wf.nodes[branch.arms["is_trial"]]
        assert type(trial_node).__name__ == "ToolNode"
        assert trial_node.tool_name == "trial_flow"

    def test_with_else(self):
        cpl = (
            'workflow "else_branch"\n'
            "    | @branch\n"
            '        -when "has_access"\n'
            "            | grant\n"
            "        -else\n"
            "            | deny\n"
        )
        wf = get_workflow(cpl, "else_branch")
        branches = find_nodes_by_type(wf, "BranchNode")
        assert len(branches) == 1
        branch = branches[0]
        assert "has_access" in branch.arms
        assert branch.else_node_id is not None

        grant_node = wf.nodes[branch.arms["has_access"]]
        assert grant_node.tool_name == "grant"

        deny_node = wf.nodes[branch.else_node_id]
        assert deny_node.tool_name == "deny"

    def test_multi_step_arms(self):
        cpl = (
            'workflow "multi_arm"\n'
            "    | @branch\n"
            '        -when "path_a"\n'
            "            | step_a1\n"
            "            | step_a2\n"
            '        -when "path_b"\n'
            "            | step_b1\n"
            "        -else\n"
            "            | fallback1\n"
            "            | fallback2\n"
        )
        wf = get_workflow(cpl, "multi_arm")
        branch = find_nodes_by_type(wf, "BranchNode")[0]

        # path_a has two steps chained
        a1 = wf.nodes[branch.arms["path_a"]]
        assert a1.tool_name == "step_a1"
        a2 = wf.nodes[a1.next_ids[0]]
        assert a2.tool_name == "step_a2"

        # path_b has one step
        b1 = wf.nodes[branch.arms["path_b"]]
        assert b1.tool_name == "step_b1"

        # else has two steps
        f1 = wf.nodes[branch.else_node_id]
        assert f1.tool_name == "fallback1"
        f2 = wf.nodes[f1.next_ids[0]]
        assert f2.tool_name == "fallback2"


class TestBranchThenContinue:
    def test_steps_after_branch(self):
        cpl = (
            'workflow "branch_then_continue"\n'
            "    | start\n"
            "    | @branch\n"
            '        -when "yes"\n'
            "            | do_yes\n"
            "        -else\n"
            "            | do_no\n"
            "    | finish\n"
        )
        wf = get_workflow(cpl, "branch_then_continue")

        # start exists
        tools = find_nodes_by_type(wf, "ToolNode")
        tool_names = {t.tool_name for t in tools}
        assert "start" in tool_names
        assert "do_yes" in tool_names
        assert "do_no" in tool_names
        assert "finish" in tool_names

        # branch exists
        branches = find_nodes_by_type(wf, "BranchNode")
        assert len(branches) == 1

        # BranchBackNode exists (merge point)
        backs = find_nodes_by_type(wf, "BranchBackNode")
        assert len(backs) == 1

        # finish comes after the merge
        back = backs[0]
        finish_id = back.next_ids[0]
        finish_node = wf.nodes[finish_id]
        assert finish_node.tool_name == "finish"


# ── Loop ──

class TestLoop:
    def test_loop_structure(self):
        cpl = (
            'workflow "looping"\n'
            "    | @loop\n"
            "        | do_work\n"
            '        -until "task_complete"\n'
        )
        wf = get_workflow(cpl, "looping")
        branches = find_nodes_by_type(wf, "BranchNode")
        assert len(branches) == 1
        loop_node = branches[0]
        assert loop_node.mode == "loop"
        assert loop_node.loop_until == "task_complete"

    def test_loop_body_contents(self):
        cpl = (
            'workflow "loop_multi"\n'
            "    | @loop\n"
            "        | check_status\n"
            "        | process_item\n"
            "        | update_counter\n"
            '        -until "all_processed"\n'
        )
        wf = get_workflow(cpl, "loop_multi")
        tools = find_nodes_by_type(wf, "ToolNode")
        tool_names = {t.tool_name for t in tools}
        assert "check_status" in tool_names
        assert "process_item" in tool_names
        assert "update_counter" in tool_names


# ── Fork / Join ──

class TestForkJoin:
    def test_fork_and_join_structure(self):
        cpl = (
            'workflow "background_task"\n'
            "    | do_bg_work\n"
            "\n"
            'workflow "forking"\n'
            "    | setup\n"
            "    | @fork bg @call background_task\n"
            "    | @join bg\n"
            "    | cleanup\n"
        )
        wf = get_workflow(cpl, "forking")

        forks = find_nodes_by_type(wf, "ForkNode")
        assert len(forks) == 1
        assert forks[0].fork_id == "bg"
        assert forks[0].workflow_name == "background_task"

        joins = find_nodes_by_type(wf, "JoinNode")
        assert len(joins) == 1
        assert joins[0].fork_id == "bg"

        tools = find_nodes_by_type(wf, "ToolNode")
        tool_names = {t.tool_name for t in tools}
        assert "setup" in tool_names
        assert "cleanup" in tool_names

    def test_fork_join_ordering(self):
        cpl = (
            'workflow "sub"\n'
            "    | sub_step\n"
            "\n"
            'workflow "ordered"\n'
            "    | before\n"
            "    | @fork x @call sub\n"
            "    | @join x\n"
            "    | after\n"
        )
        wf = get_workflow(cpl, "ordered")
        path = walk_linear(wf)
        type_names = [type(n).__name__ for n in path]
        # Should be: StartNode → ToolNode(before) → ForkNode → JoinNode → ToolNode(after) → EndNode
        assert "ForkNode" in type_names
        assert "JoinNode" in type_names
        fork_idx = type_names.index("ForkNode")
        join_idx = type_names.index("JoinNode")
        assert fork_idx < join_idx


# ── Complex workflows ──

class TestComplexWorkflow:
    def test_full_pipeline(self):
        """tool → branch → fork → join → tool — the full pipeline."""
        cpl = (
            'workflow "worker"\n'
            "    | do_worker_task\n"
            "\n"
            'workflow "complex"\n'
            "    | init\n"
            "    | @branch\n"
            '        -when "ready"\n'
            "            | proceed\n"
            "        -else\n"
            "            | abort\n"
            "    | @fork w @call worker\n"
            "    | @join w\n"
            "    | done\n"
        )
        contract = Contract.from_source(cpl)
        assert "complex" in contract.workflows
        assert "worker" in contract.workflows

        wf = contract.workflows["complex"]

        # All expected node types present
        assert len(find_nodes_by_type(wf, "BranchNode")) == 1
        assert len(find_nodes_by_type(wf, "BranchBackNode")) == 1
        assert len(find_nodes_by_type(wf, "ForkNode")) == 1
        assert len(find_nodes_by_type(wf, "JoinNode")) == 1

        tools = find_nodes_by_type(wf, "ToolNode")
        tool_names = {t.tool_name for t in tools}
        assert tool_names == {"init", "proceed", "abort", "done"}

        # Branch arm verification
        branch = find_nodes_by_type(wf, "BranchNode")[0]
        assert "ready" in branch.arms
        assert branch.else_node_id is not None

    def test_nested_branch_in_loop(self):
        cpl = (
            'workflow "nested"\n'
            "    | @loop\n"
            "        | check\n"
            "        | @branch\n"
            '            -when "found"\n'
            "                | process\n"
            "            -else\n"
            "                | skip\n"
            '        -until "exhausted"\n'
        )
        wf = get_workflow(cpl, "nested")

        # Loop node
        loop_nodes = [n for n in wf.nodes.values()
                      if type(n).__name__ == "BranchNode" and n.mode == "loop"]
        assert len(loop_nodes) == 1
        assert loop_nodes[0].loop_until == "exhausted"

        # Nested branch
        branch_nodes = [n for n in wf.nodes.values()
                        if type(n).__name__ == "BranchNode" and n.mode == "branch"]
        assert len(branch_nodes) == 1
        assert "found" in branch_nodes[0].arms
        assert branch_nodes[0].else_node_id is not None


# ── Invalid CPL ──

class TestInvalidCPL:
    def test_empty_string(self):
        with pytest.raises(Exception):
            Contract.from_source("")

    def test_workflow_no_steps(self):
        with pytest.raises(Exception):
            Contract.from_source('workflow "empty"\n')

    def test_branch_no_arms(self):
        with pytest.raises(Exception):
            Contract.from_source(
                'workflow "bad"\n'
                "    | @branch\n"
            )

    def test_loop_no_until(self):
        with pytest.raises(Exception):
            Contract.from_source(
                'workflow "bad"\n'
                "    | @loop\n"
                "        | step\n"
            )

    def test_fork_missing_workflow(self):
        """Fork referencing a workflow that doesn't exist parses but
        the workflow name is recorded — validation happens at runtime."""
        contract = Contract.from_source(
            'workflow "bad"\n'
            "    | @fork x @call nonexistent\n"
            "    | @join x\n"
        )
        wf = contract.workflows["bad"]
        forks = find_nodes_by_type(wf, "ForkNode")
        assert len(forks) == 1
        assert forks[0].workflow_name == "nonexistent"
